spring:
  profiles: dev
eureka:
  instance:
    prefer-ip-address: true #以IP地址注册到服务中心
  client:
    serviceUrl:
      defaultZone: http://123.56.27.199:8080/EurekaServer/eureka/
#      defaultZone: http://127.0.0.1:8761/eureka/
#      defaultZone: http://39.105.189.141/EurekaServer/eureka/
